# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Set environment'
  lane :set_environment do
    set_info_plist_value(path: 'Domain/Environment.plist', key: 'api_base_url', value: ENV['API_BASE_URL'])
  end

  desc 'Unit Tests'
  lane :tests do
    set_environment
    scan(
      scheme: 'Melaka',
      device: 'iPhone 14',
      code_coverage: true,
      parallel_testing: false
    )
  end

  desc 'Deploy to Test Flight'
  lane :deploy_to_test_flight do
    api_key = app_store_connect_api_key(
      key_id: ENV['ASC_KEY_ID'],
      issuer_id: ENV['ASC_ISSUER_ID'],
      key_content: ENV['ASC_API_KEY']
    )

    build_number = app_store_build_number(
      api_key: api_key,
      app_identifier: 'com.yukimaterrace.ios.melaka',
      version: get_version_number(target: 'Melaka'),
      initial_build_number: 0,
      live: false
    )
    increment_build_number(build_number: build_number + 1)

    set_environment
    build_app(
      scheme: 'Melaka',
      export_method: 'app-store'
    )

    upload_to_testflight(api_key: api_key)
  end
end
